/**
 * This file is part of vue-boilerplate.
 * @link     : https://zhaiyiming.com/
 * @author   : Emil Zhai (root@derzh.com)
 * @modifier : Emil Zhai (root@derzh.com)
 * @copyright: Copyright (c) 2018 TINYMINS.
 */

export const SAVE_SCROLL = '@@COMMON/SAVE_SCROLL';
export const REDIRECT = '@@COMMON/REDIRECT';
export const SHOW_LOADING = '@@COMMON/SHOW_LOADING';
export const HIDE_LOADING = '@@COMMON/HIDE_LOADING';
export const SHOW_TOAST = '@@COMMON/SHOW_TOAST';
export const HIDE_TOAST = '@@COMMON/HIDE_TOAST';
export const SHOW_DIALOG = '@@COMMON/SHOW_DIALOG';
export const HIDE_DIALOG = '@@COMMON/HIDE_DIALOG';
export const SHOW_ACTIONSHEET = '@@COMMON/SHOW_ACTIONSHEET';
export const HIDE_ACTIONSHEET = '@@COMMON/HIDE_ACTIONSHEET';
export const SHOW_PICKER = '@@COMMON/SHOW_PICKER';
export const HIDE_PICKER = '@@COMMON/HIDE_PICKER';
export const STORE_INSTANCE = '@@COMMON/STORE_INSTANCE';
export const HTTP_INSTANCE = '@@COMMON/HTTP_INSTANCE';
export const ROUTER_INSTANCE = '@@COMMON/ROUTER_INSTANCE';
export const ENTRY_PARAMS = '@@COMMON/ENTRY_PARAMS';
export const ROUTE_BEFORE_CHANGE = '@@COMMON/ROUTE_BEFORE_CHANGE';
export const ROUTE_CHANGE = '@@COMMON/ROUTE_CHANGE';
export const ROUTE_HISTORY_MODE = '@@COMMON/ROUTE_HISTORY_MODE';
export const SET_BODY_SCROLLABLE = '@@COMMON/SET_BODY_SCROLLABLE';
export const REMOVE_BODY_SCROLLABLE = '@@COMMON/REMOVE_BODY_SCROLLABLE';
export const SET_BODY_AUTO_HEIGHT = '@@COMMON/SET_BODY_AUTO_HEIGHT';
export const REMOVE_BODY_AUTO_HEIGHT = '@@COMMON/REMOVE_BODY_AUTO_HEIGHT';
export const SET_BODY_BACKGROUND = '@@COMMON/SET_BODY_BACKGROUND';
export const REMOVE_BODY_BACKGROUND = '@@COMMON/REMOVE_BODY_BACKGROUND';
export const SET_PAGE_TITLE = '@@COMMON/SET_PAGE_TITLE';
export const SET_VIEWPORT_SIZE = '@@COMMON/SET_VIEWPORT_SIZE';
export const SET_HEADER_HEIGHT = '@@COMMON/SET_HEADER_HEIGHT';
export const SET_HEADER_EXTRA_HEIGHT = '@@COMMON/SET_HEADER_EXTRA_HEIGHT';
export const REMOVE_HEADER_EXTRA_HEIGHT = '@@COMMON/REMOVE_HEADER_EXTRA_HEIGHT';
export const SET_TABBAR_HEIGHT = '@@COMMON/SET_TABBAR_HEIGHT';
export const SET_FOOTER_EXTRA_HEIGHT = '@@COMMON/SET_FOOTER_EXTRA_HEIGHT';
export const REMOVE_FOOTER_EXTRA_HEIGHT = '@@COMMON/REMOVE_FOOTER_EXTRA_HEIGHT';
export const SET_NAVBAR_VISIBLE = '@@COMMON/SET_NAVBAR_VISIBLE';
export const REMOVE_NAVBAR_VISIBLE = '@@COMMON/REMOVE_NAVBAR_VISIBLE';
export const SET_TABBAR_VISIBLE = '@@COMMON/SET_TABBAR_VISIBLE';
export const REMOVE_TABBAR_VISIBLE = '@@COMMON/REMOVE_TABBAR_VISIBLE';
export const GET_WECHAT_SDK_INFO = '@@COMMON/GET_WECHAT_SDK_INFO';
export const SET_PAGE_SHARE = '@@COMMON/SET_PAGE_SHARE';
